## **Naive Bayes**

### **From Scratch**

In [93]:
import pandas as pd
import numpy as np

In [94]:
df = pd.read_csv("./data/play_tennis.csv")
df.head()

day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [95]:
df.shape

(14, 6)

In [96]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [97]:
py = 9/14
pn = 5/14
print(py,pn)

0.6428571428571429 0.35714285714285715


**`Outlook column`**

In [98]:
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook          
Overcast   0    4
Rain       2    3
Sunny      3    2

In [99]:
p_overcast_n = 0/5
p_rain_n = 2/5
p_sunny_n = 3/5

p_overcast_y = 4/5
p_rain_y = 3/5
p_sunny_y = 2/5

**`Temp column`**

In [100]:
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp         
Cool   1    3
Hot    2    2
Mild   2    4

In [101]:
p_cool_n = 1/5
p_hot_n = 2/5
p_mild_n = 2/5

p_cool_y = 3/9
p_hot_y = 2/9
p_mild_n = 4/9

**`Humidity column`**

In [102]:
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity         
High       4    3
Normal     1    6

In [103]:
p_high_n = 4/5
p_normal_n = 1/5

p_high_y = 3/9
p_normal_y = 6/9

**`Wind column`**

In [104]:
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind           
Strong   3    3
Weak     2    6

In [105]:
p_strong_n = 3/5
p_weak_n = 2/5

p_strong_y = 3/9
p_weak_y = 6/9

**`Problem`**

- Outlook = sunny , temp = hot , humidity = high , wind = weak

In [106]:
P_Yes = p_sunny_y * p_hot_y * p_high_y * p_weak_y * py
print(P_Yes)

0.012698412698412698


In [107]:
P_No = p_sunny_n * p_hot_n * p_high_n * p_weak_n * pn
print(P_No)

0.02742857142857143


In [109]:
P_Yes = p_sunny_y * p_hot_y * p_high_y * p_weak_y * py
P_No = p_sunny_n * p_hot_n * p_high_n * p_weak_n * pn

# Prediction
if P_Yes > P_No:
    print("It's a Game Day")
else:
    print("It's Not a Game Day")

It's Not a Game Day


### **Using Sk-Learn**

In [118]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.datasets import load_iris

In [119]:
X, y = load_iris(return_X_y=True)

In [120]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [121]:
gnb = GaussianNB()

In [122]:
gnb.fit(X_train,y_train)

GaussianNB()

In [123]:
y_pred=gnb.predict(X_test)

In [127]:
print("Accuracy Score:",accuracy_score(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))

Accuracy Score: 0.9777777777777777
Confusion Matrix:
 [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
